on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install node_modules
        run: npm install
      - name: build
        run: npm run build
      - name: Deploy
        run: |
          /usr/bin/git config user.name "uzimaru0000"
          /usr/bin/git config user.email "shuji365630@gmail.com"
          /usr/bin/git remote rm origin
          /usr/bin/git remote add origin https://uzimaru0000:${{ secrets.ACCESS_TOKEN }}@github.com/uzimaru0000/uzimaru0000.github.io.git
          /usr/bin/git rm -r --ignore-unmatch *
          cp dist/* ./
          /usr/bin/git add .
          /usr/bin/git commit -m "deploy"
          /usr/bin/git push origin master
